name: build cosi controller container image

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 0 * * *' # every day at midnight

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout kubernetes-sigs/container-object-storage-interface-controller
      uses: actions/checkout@v2
      with:
        repository: kubernetes-sigs/container-object-storage-interface-controller
        
    - name: Login to Quay.io
      uses: docker/login-action@v1
      with:
        logout: true
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}        

    - name: Build and push the container image
      run: |
        make clean
        make push
        
