name: build cosi provisioner and sidecar container images

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 0 * * *' # every day at midnight

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout kubernetes-sigs/container-object-storage-interface-provisioner-sidecar
      uses: actions/checkout@v2
      with:
        repository: kubernetes-sigs/container-object-storage-interface-provisioner-sidecar
        
    - name: Login to Quay.io
      uses: docker/login-action@v1
      with:
        logout: true
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}        

    - name: Build and push the container image
      run: |
        echo "REGISTRY_NAME=quay.io/containerobjectstorage" >> Makefile
        echo "IMAGE_TAGS=canary" >> Makefile
        make clean && \
          make test && \
          make push && \
          docker tag sample-driver:latest quay.io/containerobjectstorage/objectstorage-sample-driver:canary && \
          docker push quay.io/containerobjectstorage/objectstorage-sample-driver:canary


